apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecquest-frontend
  labels:
    app: devsecquest
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecquest
      component: frontend
  template:
    metadata:
      labels:
        app: devsecquest
        component: frontend
    spec:
      containers:
      - name: frontend
        image: devsecquest-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: devsecquest-frontend
  labels:
    app: devsecquest
    component: frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    app: devsecquest
    component: frontend 